function Data = CalculatePosition(Data)
for i = 1:length(Data)
    Data(i).XPosition = ...
        cumtrapz(Data(i).TimeInSeconds, ...
        Data(i).XGyro - mean(Data(i).XGyro));
    Data(i).YPosition = ...
        cumtrapz(Data(i).TimeInSeconds, ...
        Data(i).YGyro - mean(Data(i).YGyro));
    Data(i).ZPosition = ...
        cumtrapz(Data(i).TimeInSeconds, ...
        Data(i).ZGyro - mean(Data(i).ZGyro));
end