function FilteredData = ...
    FilterData(DownsampledData, NumberOfPointsInMovingAverageFilter)

a = 1; 
b(1:NumberOfPointsInMovingAverageFilter) = ...
    1 / NumberOfPointsInMovingAverageFilter; 

for i = 1:length(DownsampledData)
    FilteredData(i).Filename = ...
        DownsampledData(i).Filename; 
    FilteredData(i).Run = ...
        DownsampledData(i).Run; 
    FilteredData(i).TimeInSeconds = ...
        DownsampledData(i).TimeInSeconds; 
    FilteredData(i).XGyro = ...
        filter(b, a, DownsampledData(i).XGyro); 
    FilteredData(i).YGyro = ...
        filter(b, a, DownsampledData(i).YGyro); 
    FilteredData(i).ZGyro = ...
        filter(b, a, DownsampledData(i).ZGyro); 
end