function Data = ...
    FilterFFTData(Data, NumberOfPointsInMovingAverageFilter)

a = 1; 
b(1:NumberOfPointsInMovingAverageFilter) = ...
    1 / NumberOfPointsInMovingAverageFilter; 

for i = 1:length(Data)
    Data(i).FilteredXFrequency = ...
        filter(b, a, Data(i).XFrequency); 
    Data(i).FilteredYFrequency = ...
        filter(b, a, Data(i).YFrequency); 
    Data(i).FilteredZFrequency = ...
        filter(b, a, Data(i).ZFrequency); 
end