RunFrequencyData = vertcat(Data.PrincipalXFrequency(RunConcreteShoesIndices), ...
    Data.PrincipalZFrequency(RunConcreteShoesIndices ),...
    Data.PrincipalYFrequency( RunConcreteShoesIndices ), ...
    Data.PrincipalXFrequency(RunInPlaceIndices) , ...
    Data.PrincipalZFrequency(RunInPlaceIndices ), ...
    Data.PrincipalYFrequency( RunInPlaceIndices ), ...
    Data.PrincipalXFrequency(RunGrassShoesIndices) , ...
    Data.PrincipalZFrequency(RunGrassShoesIndices ), ...
    Data.PrincipalYFrequency( RunGrassShoesIndices ) ); 

RunGyroData = vertcat(Data.MaxXGyro(RunConcreteShoesIndices), ...
    Data.MaxZGyro(RunConcreteShoesIndices ),...
    Data.MaxYGyro( RunConcreteShoesIndices ), ...
    Data.MaxXGyro(RunInPlaceIndices) , ...
    Data.MaxZGyro(RunInPlaceIndices ), ...
    Data.MaxYGyro( RunInPlaceIndices ), ...
    Data.MaxXGyro(RunGrassShoesIndices) , ...
    Data.MaxZGyro(RunGrassShoesIndices ), ...
    Data.MaxYGyro( RunGrassShoesIndices ) ); 

WalkFrequencyData = vertcat(...
    Data.PrincipalXFrequency(WalkConcreteShoesIndices), ...
    Data.PrincipalZFrequency(WalkConcreteShoesIndices), ...
    Data.PrincipalYFrequency(WalkConcreteShoesIndices), ...
    Data.PrincipalXFrequency(WalkInPlaceIndices), ...
    Data.PrincipalZFrequency(WalkInPlaceIndices), ...
    Data.PrincipalYFrequency(WalkInPlaceIndices), ...
    Data.PrincipalXFrequency(WalkGrassShoesIndices), ...
    Data.PrincipalZFrequency(WalkGrassShoesIndices), ...
    Data.PrincipalYFrequency(WalkGrassShoesIndices) ) ; 

WalkGyroData = vertcat(...
    Data.MaxXGyro(WalkConcreteShoesIndices), ...
    Data.MaxZGyro(WalkConcreteShoesIndices), ...
    Data.MaxYGyro(WalkConcreteShoesIndices), ...
    Data.MaxXGyro(WalkInPlaceIndices), ...
    Data.MaxZGyro(WalkInPlaceIndices), ...
    Data.MaxYGyro(WalkInPlaceIndices), ...
    Data.MaxXGyro(WalkGrassShoesIndices), ...
    Data.MaxZGyro(WalkGrassShoesIndices), ...
    Data.MaxYGyro(WalkGrassShoesIndices) ) ; 

ShakeFrequencyData = vertcat( ...
    Data.PrincipalXFrequency(HorizontalShakeIndices), ...
    Data.PrincipalZFrequency(HorizontalShakeIndices), ...
    Data.PrincipalYFrequency(HorizontalShakeIndices), ...
    Data.PrincipalXFrequency(VerticalShakeIndices), ...
    Data.PrincipalZFrequency(VerticalShakeIndices), ...
    Data.PrincipalYFrequency(VerticalShakeIndices)); 

ShakeGyroData = vertcat( ...
    Data.MaxXGyro(HorizontalShakeIndices), ...
    Data.MaxZGyro(HorizontalShakeIndices), ...
    Data.MaxYGyro(HorizontalShakeIndices), ...
    Data.MaxXGyro(VerticalShakeIndices), ...
    Data.MaxZGyro(VerticalShakeIndices), ...
    Data.MaxYGyro(VerticalShakeIndices) ); 