%% Get Run data
RunFrequencyData = vertcat(Data.PrincipalXFrequency(RunConcreteShoesIndices), ...
    Data.PrincipalZFrequency(RunConcreteShoesIndices ),...
    Data.PrincipalYFrequency( RunConcreteShoesIndices ), ...
    Data.PrincipalXFrequency(RunInPlaceIndices) , ...
    Data.PrincipalZFrequency(RunInPlaceIndices ), ...
    Data.PrincipalYFrequency( RunInPlaceIndices ), ...
    Data.PrincipalXFrequency(RunGrassShoesIndices) , ...
    Data.PrincipalZFrequency(RunGrassShoesIndices ), ...
    Data.PrincipalYFrequency( RunGrassShoesIndices ) ); 

RunGyroData = vertcat(Data.MaxXGyro(RunConcreteShoesIndices), ...
    Data.MaxZGyro(RunConcreteShoesIndices ),...
    Data.MaxYGyro( RunConcreteShoesIndices ), ...
    Data.MaxXGyro(RunInPlaceIndices) , ...
    Data.MaxZGyro(RunInPlaceIndices ), ...
    Data.MaxYGyro( RunInPlaceIndices ), ...
    Data.MaxXGyro(RunGrassShoesIndices) , ...
    Data.MaxZGyro(RunGrassShoesIndices ), ...
    Data.MaxYGyro( RunGrassShoesIndices ) ); 

RunMaxAmplitudeData = vertcat(Data.MaxXAmplitude(RunConcreteShoesIndices), ...
    Data.MaxZAmplitude(RunConcreteShoesIndices ),...
    Data.MaxYAmplitude( RunConcreteShoesIndices ), ...
    Data.MaxXAmplitude(RunInPlaceIndices) , ...
    Data.MaxZAmplitude(RunInPlaceIndices ), ...
    Data.MaxYAmplitude( RunInPlaceIndices ), ...
    Data.MaxXAmplitude(RunGrassShoesIndices) , ...
    Data.MaxZAmplitude(RunGrassShoesIndices ), ...
    Data.MaxYAmplitude( RunGrassShoesIndices ) ); 

RunMedianAmplitudeData = vertcat(Data.MedianXAmplitude(RunConcreteShoesIndices), ...
    Data.MedianZAmplitude(RunConcreteShoesIndices ),...
    Data.MedianYAmplitude( RunConcreteShoesIndices ), ...
    Data.MedianXAmplitude(RunInPlaceIndices) , ...
    Data.MedianZAmplitude(RunInPlaceIndices ), ...
    Data.MedianYAmplitude( RunInPlaceIndices ), ...
    Data.MedianXAmplitude(RunGrassShoesIndices) , ...
    Data.MedianZAmplitude(RunGrassShoesIndices ), ...
    Data.MedianYAmplitude( RunGrassShoesIndices ) ); 

%% Get Walk data
WalkFrequencyData = vertcat(...
    Data.PrincipalXFrequency(WalkConcreteShoesIndices), ...
    Data.PrincipalZFrequency(WalkConcreteShoesIndices), ...
    Data.PrincipalYFrequency(WalkConcreteShoesIndices), ...
    Data.PrincipalXFrequency(WalkInPlaceIndices), ...
    Data.PrincipalZFrequency(WalkInPlaceIndices), ...
    Data.PrincipalYFrequency(WalkInPlaceIndices), ...
    Data.PrincipalXFrequency(WalkGrassShoesIndices), ...
    Data.PrincipalZFrequency(WalkGrassShoesIndices), ...
    Data.PrincipalYFrequency(WalkGrassShoesIndices) ) ; 

WalkGyroData = vertcat(...
    Data.MaxXGyro(WalkConcreteShoesIndices), ...
    Data.MaxZGyro(WalkConcreteShoesIndices), ...
    Data.MaxYGyro(WalkConcreteShoesIndices), ...
    Data.MaxXGyro(WalkInPlaceIndices), ...
    Data.MaxZGyro(WalkInPlaceIndices), ...
    Data.MaxYGyro(WalkInPlaceIndices), ...
    Data.MaxXGyro(WalkGrassShoesIndices), ...
    Data.MaxZGyro(WalkGrassShoesIndices), ...
    Data.MaxYGyro(WalkGrassShoesIndices) ) ; 

WalkMaxAmplitudeData = vertcat(...
    Data.MaxXAmplitude(WalkConcreteShoesIndices), ...
    Data.MaxZAmplitude(WalkConcreteShoesIndices), ...
    Data.MaxYAmplitude(WalkConcreteShoesIndices), ...
    Data.MaxXAmplitude(WalkInPlaceIndices), ...
    Data.MaxZAmplitude(WalkInPlaceIndices), ...
    Data.MaxYAmplitude(WalkInPlaceIndices), ...
    Data.MaxXAmplitude(WalkGrassShoesIndices), ...
    Data.MaxZAmplitude(WalkGrassShoesIndices), ...
    Data.MaxYAmplitude(WalkGrassShoesIndices) ) ; 

WalkMedianAmplitudeData = vertcat(...
    Data.MedianXAmplitude(WalkConcreteShoesIndices), ...
    Data.MedianZAmplitude(WalkConcreteShoesIndices), ...
    Data.MedianYAmplitude(WalkConcreteShoesIndices), ...
    Data.MedianXAmplitude(WalkInPlaceIndices), ...
    Data.MedianZAmplitude(WalkInPlaceIndices), ...
    Data.MedianYAmplitude(WalkInPlaceIndices), ...
    Data.MedianXAmplitude(WalkGrassShoesIndices), ...
    Data.MedianZAmplitude(WalkGrassShoesIndices), ...
    Data.MedianYAmplitude(WalkGrassShoesIndices) ) ; 

%% Get Shake data

ShakeFrequencyData = vertcat( ...
    Data.PrincipalXFrequency(HorizontalShakeIndices), ...
    Data.PrincipalZFrequency(HorizontalShakeIndices), ...
    Data.PrincipalYFrequency(HorizontalShakeIndices), ...
    Data.PrincipalXFrequency(VerticalShakeIndices), ...
    Data.PrincipalZFrequency(VerticalShakeIndices), ...
    Data.PrincipalYFrequency(VerticalShakeIndices)); 

ShakeGyroData = vertcat( ...
    Data.MaxXGyro(HorizontalShakeIndices), ...
    Data.MaxZGyro(HorizontalShakeIndices), ...
    Data.MaxYGyro(HorizontalShakeIndices), ...
    Data.MaxXGyro(VerticalShakeIndices), ...
    Data.MaxZGyro(VerticalShakeIndices), ...
    Data.MaxYGyro(VerticalShakeIndices) ); 

ShakeMaxAmplitudeData = vertcat( ...
    Data.MaxXAmplitude(HorizontalShakeIndices), ...
    Data.MaxZAmplitude(HorizontalShakeIndices), ...
    Data.MaxYAmplitude(HorizontalShakeIndices), ...
    Data.MaxXAmplitude(VerticalShakeIndices), ...
    Data.MaxZAmplitude(VerticalShakeIndices), ...
    Data.MaxYAmplitude(VerticalShakeIndices) ); 

ShakeMedianAmplitudeData = vertcat( ...
    Data.MedianXAmplitude(HorizontalShakeIndices), ...
    Data.MedianZAmplitude(HorizontalShakeIndices), ...
    Data.MedianYAmplitude(HorizontalShakeIndices), ...
    Data.MedianXAmplitude(VerticalShakeIndices), ...
    Data.MedianZAmplitude(VerticalShakeIndices), ...
    Data.MedianYAmplitude(VerticalShakeIndices) ); 