function outval = WriteDataStatsToFile(Data, OutputFilename)
fid = fopen(OutputFilename, 'w'); 
fprintf(fid, '%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n', ...
    'Filename', 'Run', ...
    'MaxXGyro', 'MaxYGyro', 'MaxZGyro', ...
    'PrincipalXFrequency', 'PrincipalYFrequency', 'PrincipalZFrequency', ...
    'MaxXAmplitude', 'MaxYAmplitude', 'MaxZAmplitude', ...
    'MedianXAmplitude', 'MedianYAmplitude', 'MedianZAmplitude'); 
fclose(fid); 

fid = fopen(OutputFilename, 'a'); 
for i = 1:length(Data)
    fprintf(fid, '%s,%d,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f,%f\n', ...
        Data(i).Filename, ...
        Data(i).Run, ...
        max(Data(i).XGyro),...
        max(Data(i).YGyro), ...
        max(Data(i).ZGyro), ...
        Data(i).Frequencies(Data(i).FilteredXFrequency == ...
            max(Data(i).FilteredXFrequency)), ...
        Data(i).Frequencies(Data(i).FilteredYFrequency == ...
            max(Data(i).FilteredYFrequency)), ...
        Data(i).Frequencies(Data(i).FilteredZFrequency == ...
            max(Data(i).FilteredZFrequency)), ...
        max(Data(i).XAmplitude), ...
        max(Data(i).YAmplitude), ...
        max(Data(i).ZAmplitude), ...
        median(Data(i).XAmplitude), ...
        median(Data(i).YAmplitude), ...
        median(Data(i).ZAmplitude) );
end